filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/myapp/application.log
    multiline.pattern: '^20\d{2}-\d{2}-\d{2}'
    multiline.negate: true
    multiline.match: after

output.logstash:
  hosts: ["logstash:5044"]
